openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

# Actions sur nos clients ! (En ajouter, les voir)
# ---
# paths:
#   /users:
#     post:
#       summary: Adds a new user
#       requestBody:
#         content:
#           application/json:
#             schema:      # Request body contents
#               type: object
#               properties:
#                 id:
#                   type: integer
#                 name:
#                   type: string
#               example:   # Sample object
#                 id: 10
#                 name: Jessica Smith
#       responses:
#         '200':
#           description: OK